#!/usr/bin/env bash
#install and cofigure HAproxy

ha_config="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 530550-web-01 52.91.154.62:80 check
    server 530550-web-02 54.166.175.242:80 check
"

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

apt-get -y install haproxy
echo "$ha_config" >> /etc/haproxy/haproxy.cfg
service haproxy restart
