#!/usr/bin/env bash
# this script parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code
#   Displays the number of occurrences, IP, and HTTP status code in sorted order.

myfile="apache-access.log"
awk -F' ' '{ print $1, $9}' $myfile | sort | uniq -c|sort -nr
