#!/usr/bin/env bash
# This script displays "Best school" 10 times
#+ also displays hi on the 9th iteration
x=0
while [ "$x" -lt 10 ]
do
   echo "Best School"
   if [ "$x" -eq 8 ]
   then
       echo "Hi"
   fi
   x=$((x+1))
done
