#!/usr/bin/env bash
# displays "Best School" 20 times except for the
x=1
while [ "$x" -le 20 ]
do
    echo "$x"
    case $x in
      4)
        echo "bad luck from China"
        ;;
      9)
        echo "bad luck from Japan"
        ;;
      17)
        echo "bad luck from Italy"
	;;
     esac
     x=$((x+1))
done
