#!/usr/bin/env bash
# run nginx server with nginx previleges (not root)

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf

sudo -u nginx service nginx start
